
export type DateFlashcard = {
  event: string;
  date: string;
};

export type KeyDatesData = {
  [key: string]: {
    title: string;
    dates: DateFlashcard[];
  };
};

export const keyDates: KeyDatesData = {
  'cold-war': {
    title: 'Superpower Relations and the Cold War',
    dates: [
      { event: 'Tehran Conference', date: 'Nov 1943' },
      { event: 'Yalta Conference', date: 'Feb 1945' },
      { event: 'End of WWII in Europe', date: 'May 1945' },
      { event: 'Potsdam Conference', date: 'Jul-Aug 1945' },
      { event: 'USA drops atomic bombs on Japan', date: 'Aug 1945' },
      { event: 'Iron Curtain Speech by Churchill', date: 'Mar 1946' },
      { event: 'Truman Doctrine announced', date: 'Mar 1947' },
      { event: 'Marshall Plan introduced', date: 'Jun 1947' },
      { event: 'Cominform established', date: 'Oct 1947' },
      { event: 'Berlin Blockade begins', date: 'Jun 1948' },
      { event: 'Comecon established', date: 'Jan 1949' },
      { event: 'NATO formed', date: 'Apr 1949' },
      { event: 'Berlin Blockade ends', date: 'May 1949' },
      { event: 'USSR develops atomic bomb', date: 'Aug 1949' },
      { event: 'Korean War begins', date: 'Jun 1950' },
      { event: 'Death of Stalin', date: 'Mar 1953' },
      { event: 'Korean War ends', date: 'Jul 1953' },
      { event: 'Warsaw Pact formed', date: 'May 1955' },
      { event: 'Khrushchev\'s \'Secret Speech\'', date: 'Feb 1956' },
      { event: 'Hungarian Uprising', date: 'Oct-Nov 1956' },
      { event: 'Berlin Ultimatum issued by Khrushchev', date: 'Nov 1958' },
      { event: 'Bay of Pigs invasion', date: 'Apr 1961' },
      { event: 'Berlin Wall built', date: 'Aug 1961' },
      { event: 'Cuban Missile Crisis', date: 'Oct 1962' },
      { event: 'Prague Spring begins', date: 'Jan 1968' },
      { event: 'Nuclear Non-Proliferation Treaty', date: 'Jul 1968' },
      { event: 'Soviet invasion of Czechoslovakia', date: 'Aug 1968' },
      { event: 'Brezhnev Doctrine announced', date: 'Nov 1968' },
      { event: 'SALT I signed', date: 'May 1972' },
      { event: 'Helsinki Accords', date: 'Aug 1975' },
      { event: 'Soviet invasion of Afghanistan', date: 'Dec 1979' },
      { event: 'Carter Doctrine announced', date: 'Jan 1980' },
      { event: 'Reagan\'s \'Evil Empire\' speech', date: 'Mar 1983' },
      { event: 'Gorbachev becomes leader of USSR', date: 'Mar 1985' },
      { event: 'INF Treaty signed', date: 'Dec 1987' },
      { event: 'Fall of the Berlin Wall', date: 'Nov 1989' },
      { event: 'Reunification of Germany', date: 'Oct 1990' },
      { event: 'Warsaw Pact dissolved', date: 'Jul 1991' },
      { event: 'Collapse of the Soviet Union', date: 'Dec 1991' },
    ],
  },
  'weimar-nazi-germany': {
    title: 'Weimar and Nazi Germany',
    dates: [
      { event: 'Kaiser Wilhelm II abdicates', date: '9 Nov 1918' },
      { event: 'Armistice signed', date: '11 Nov 1918' },
      { event: 'Spartacist Uprising', date: 'Jan 1919' },
      { event: 'Treaty of Versailles signed', date: 'Jun 1919' },
      { event: 'Weimar Constitution established', date: 'Aug 1919' },
      { event: 'Nazi Party (NSDAP) founded', date: 'Feb 1920' },
      { event: 'Kapp Putsch', date: 'Mar 1920' },
      { event: 'French occupation of the Ruhr', date: 'Jan 1923' },
      { event: 'Hyperinflation peaks in Germany', date: 'Nov 1923' },
      { event: 'Munich (Beer Hall) Putsch', date: 'Nov 1923' },
      { event: 'Dawes Plan agreed', date: 'Aug 1924' },
      { event: 'Locarno Pact signed', date: 'Dec 1925' },
      { event: 'Germany joins League of Nations', date: 'Sep 1926' },
      { event: 'Kellogg-Briand Pact signed', date: 'Aug 1928' },
      { event: 'Young Plan agreed', date: 'Jun 1929' },
      { event: 'Wall Street Crash', date: 'Oct 1929' },
      { event: 'Hitler appointed Chancellor', date: 'Jan 1933' },
      { event: 'Reichstag Fire', date: 'Feb 1933' },
      { event: 'Enabling Act passed', date: 'Mar 1933' },
      { event: 'First concentration camp (Dachau) opens', date: 'Mar 1933' },
      { event: 'Trade Unions banned', date: 'May 1933' },
      { event: 'Night of the Long Knives', date: 'Jun 1934' },
      { event: 'Death of Hindenburg; Hitler becomes Führer', date: 'Aug 1934' },
      { event: 'Nuremberg Laws introduced', date: 'Sep 1935' },
      { event: 'Remilitarisation of the Rhineland', date: 'Mar 1936' },
      { event: 'Anschluss with Austria', date: 'Mar 1938' },
      { event: 'Kristallnacht (Night of Broken Glass)', date: 'Nov 1938' },
      { event: 'Invasion of Poland; WWII begins', date: 'Sep 1939' },
    ],
  },
  'medicine-in-britain': {
    title: 'Medicine in Britain',
    dates: [
      { event: 'The Black Death arrives in England', date: '1348' },
      { event: 'First printing press in England', date: '1476' },
      { event: 'Vesalius publishes "On the Fabric of the Human Body"', date: '1543' },
      { event: 'William Harvey publishes discovery of blood circulation', date: '1628' },
      { event: 'The Great Plague of London', date: '1665' },
      { event: 'First vaccination (Jenner) for smallpox', date: '1796' },
      { event: 'Jenner\'s findings on vaccination published', date: '1798' },
      { event: 'First cholera epidemic in Britain', date: '1831-32' },
      { event: 'Edwin Chadwick\'s "Sanitary Report"', date: '1842' },
      { event: 'Ether used as anaesthetic by Robert Liston', date: '1846' },
      { event: 'James Simpson discovers anaesthetic properties of chloroform', date: '1847' },
      { event: 'First Public Health Act', date: '1848' },
      { event: 'John Snow links cholera to contaminated water', date: '1854' },
      { event: 'Florence Nightingale publishes "Notes on Nursing"', date: '1859' },
      { event: 'Louis Pasteur publishes his Germ Theory', date: '1861' },
      { event: 'Joseph Lister uses carbolic acid as an antiseptic', date: '1867' },
      { event: 'Second Public Health Act', date: '1875' },
      { event: 'Robert Koch identifies bacteria causing anthrax', date: '1876' },
      { event: 'Koch identifies bacteria causing tuberculosis', date: '1882' },
      { event: 'X-rays discovered by Wilhelm Röntgen', date: '1895' },
      { event: 'Boer War highlights poor health of recruits', date: '1899-1902' },
      { event: 'Liberal Social Reforms (incl. free school meals)', date: '1906-1914' },
      { event: 'Alexander Fleming discovers penicillin', date: '1928' },
      { event: 'Florey and Chain develop penicillin into a usable drug', date: '1940' },
      { event: 'Beveridge Report published', date: '1942' },
      { event: 'NHS (National Health Service) is launched', date: '1948' },
      { event: 'Crick and Watson publish structure of DNA', date: '1953' },
      { event: 'First heart transplant in Britain', date: '1968' },
      { event: 'First smoking ban in public places in UK', date: '2007' },
    ],
  },
  'anglo-saxon-norman-england': {
    title: 'Anglo-Saxon and Norman England',
    dates: [
      { event: 'Godwin becomes Earl of Wessex', date: 'c.1018' },
      { event: 'Harold Godwinson\'s embassy to Normandy', date: '1064' },
      { event: 'Tostig Godwinson exiled', date: '1065' },
      { event: 'Death of Edward the Confessor', date: '5 Jan 1066' },
      { event: 'Harold Godwinson crowned King of England', date: '6 Jan 1066' },
      { event: 'Battle of Gate Fulford', date: '20 Sep 1066' },
      { event: 'Battle of Stamford Bridge', date: '25 Sep 1066' },
      { event: 'William of Normandy lands at Pevensey', date: '28 Sep 1066' },
      { event: 'Battle of Hastings', date: '14 Oct 1066' },
      { event: 'William the Conqueror crowned King', date: '25 Dec 1066' },
      { event: 'Revolt of Edwin and Morcar', date: '1068' },
      { event: 'Harrying of the North begins', date: '1069' },
      { event: 'Hereward the Wake\'s rebellion at Ely', date: '1070-71' },
      { event: 'Revolt of the Earls (Roger, Ralph, and Waltheof)', date: '1075' },
      { event: 'Domesday Book commissioned', date: 'Dec 1085' },
      { event: 'Domesday Book completed', date: 'Aug 1086' },
      { event: 'Death of William the Conqueror', date: '9 Sep 1087' },
      { event: 'Rebellion against William II', date: '1088' },
    ],
  },
};
